# Generated by Django 4.2.7 on 2023-11-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_question_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_displayed',
            field=models.BooleanField(default=False),
        ),
    ]
