# Generated by Django 4.2.7 on 2023-11-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_question_answer_displayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_displayed',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
