# Generated by Django 4.2.7 on 2023-11-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_mark_question_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
