# Generated by Django 4.2.7 on 2023-11-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_mark_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='topic',
        ),
        migrations.AlterField(
            model_name='mark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
