# Generated by Django 4.2.7 on 2023-11-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_mark_topic_alter_mark_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='game.topic'),
            preserve_default=False,
        ),
    ]
